version: '3.8'

services:
  bot_db:
    container_name: bot_db
    image: postgres:14.2
    ports:
      - "5432:5432"
    #    expose:
    #      - 5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - data-bot_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

  bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped

    environment:
      - ENV=${ENV:-production}
      - BOT_TOKEN=${BOT_TOKEN}
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - LOG_LEVEL=INFO
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TEMPERATURE=${TEMPERATURE}
      - MAX_TOKENS=${MAX_TOKENS}
      - MAX_HISTORY_LENGTH=${MAX_HISTORY_LENGTH}

    # Или используй .env файл
#    env_file:
#      - .env.prod

    volumes:
      - ./logs:/var/app/logs

    command: python3 -m main

    depends_on:
      bot_db:
        condition: service_healthy

    networks:
      - bot_network

volumes:
  data-bot_db:
    driver: local

networks:
  bot_network:
    driver: bridge
